USE [911Linx]
GO
-- SOLUTION: 911NWS
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetAuthenticationExpired', N'GET', N'https://localhost:8022/911Linx/API/Authentication/Expired?Server={server}&Application={application}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetApiKey', N'GET', N'https://localhost:8022/911Linx/API/Authentication/ApiKey?Server={server}&Application={application}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetTable', N'GET', N'https://localhost:8022/911Linx/API/Application/GetTable?Server={server}&Application={application}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'SetTable', N'POST', N'https://localhost:8022/911Linx/API/Application/SetTable?Server={server}&Application={application}', N'application/json', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetHeader', N'GET', N'https://localhost:8022/911Linx/API/Application/GetHeader?Server={server}&Application={application}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'SetHeader', N'POST', N'https://localhost:8022/911Linx/API/Application/SetHeaderTable?Server={server}&Application={application}', N'application/json', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetHeaderTable', N'GET', N'https://localhost:8022/911Linx/API/Application/GetHeaderTable?Server={server}&Application={application}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetCredentials', N'GET', N'https://localhost:8022/911Linx/API/Application/GetCredential?Server={server}&Application={application}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'SetCredentials', N'POST', N'https://localhost:8022/911Linx/API/Application/SetCredential?Server={server}&Application={application}', N'application/json', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetSettings', N'GET', N'https://localhost:8022/911Linx/API/Application/GetSettings?Server={server}&Application={application}&Activity={activity}&Process={process}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'GetLog', N'GET', N'https://localhost:8022/911Linx/API/Log/GetLog?Server={server}&Application={application}', N'', N'application/json', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'Log', N'POST', N'https://localhost:8022/911Linx/API/Log', N'application/json', N'', SYSDATETIMEOFFSET()))
INSERT [911].[LinxAppUrlMapping] ([ApplicationID], [Activity], [Action], [Method], [Url], [RequestContentType], [ResponseContentType], [TimeCreated]) VALUES (27, N'Application', N'SendEmail', N'POST', N'https://localhost8022/911Linx/API/Notification/SendEmail?Server={server}&Application={application}', N'application/json', N'application/json', SYSDATETIMEOFFSET()))
GO